language: c
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      if: branch = main
      env: 
        - BUILD_TARGET=ios
        - BUILD_ARCH=arm
        - TRAVIS_CI=true

install:
  - echo "Nothing to install"

script:
  - BUILDWARE_ROOT=`pwd`
  - INSTALL_ROOT="install_${BUILD_TARGET}_${BUILD_ARCH}"
  - mkdir -p "buildsrc"
  - source 1k/build1.sh luajit $BUILD_TARGET $BUILD_ARCH $INSTALL_ROOT
  - export INSTALL_ROOT=$INSTALL_ROOT
  - zip -q -r ${INSTALL_ROOT}.zip ${INSTALL_ROOT}

before_deploy:
  # Set up git user name and tag this commit
  - export TRAVIS_TAG=$(git log --format=%h -1)
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "release-bot"
  - git config --local user.email "release-bot@users.noreply.github.com"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - install_ios_arm.zip
  on:
    branch: main
    repo: halx99/buildware

notifications:
  email:
    on_success: never
    on_failure: always
