#
# Copyright (c) 2021 Bytedance Inc.
#

name: distall-ci

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ dev ]
  # push:
  #   tags:
  #     - 'v*.*.*'
  # workflow_run:
  #   workflows: ["buildall-ci"]
  #   types: [completed]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      run_id:
        # actions run ID
        description: 'Please specific buildall-ci run id to dist'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false
      release_tag:
        # actions run ID
        description: 'Please specific a exists release tag name, such as 1.0.0'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  dist:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v2
    
    - name: Download artifact from workflow buildall-ci
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: buildall-ci.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion::
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        # "completed", "in_progress", "queued"
        # Default: "completed,success"
        workflow_conclusion: success
        # Optional, will get head commit SHA
        # pr: ${{github.event.pull_request.number}}
        # Optional, no need to specify if PR is
        # commit: ${{github.event.pull_request.head.sha}}
        # Optional, will use the branch
        branch: dev
        # Optional, defaults to all types
        # event: push
        # Optional, if not specified, the artifact from the most recent successfully completed workflow run will be downloaded
        # run_id: ${{ github.event.inputs.run_id }}
        # Optional, run number from the workflow
        # run_number: 34
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        # name: artifact_name
        # Optional, directory where to extract artifact
        # path: openssl-dist-src
        # Optional, defaults to current repo
        # repo: ${{github.repository}}

    - name: Prepare dist package
      run: |
        echo "Checking download structure"
        ls -R
    # - name: Upload dist package to artifact page
    #   uses: actions/upload-artifact@v2
    #   with:
    #     path: ./${{ env.DIST_PACKAGE }}
    #     name: ${{ env.DIST_NAME }}

    - name: Parse release tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "RELEASE_TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Determine release tag name from input
      run: |
        if [ "$RELEASE_TAG_NAME" = "" ]; then
          RELEASE_TAG_NAME=${{github.event.inputs.release_tag}}
          echo "RELEASE_TAG_NAME=$RELEASE_TAG_NAME" >> $GITHUB_ENV
        fi
    - name: Upload dist package to release page
      if: ${{ env.RELEASE_TAG_NAME != '' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG_NAME }}
        name: ${{ env.DIST_NAME }}_${{ env.RELEASE_TAG_NAME }}
        files: ${{ env.DIST_PACKAGE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: adxeproject/buildware
